---
# Variable configuration.
- include_tasks: variables.yml

- name: Ensure PostgreSQL privs are present.
  postgresql_privs:
    roles: "{{ item.name }}"
    db: "{{ item.db }}"
    grant_option: "{{item.grant_option | default('no') }}"
    objs: "{{ item.objs | default(omit) }}"
    privs: "{{ item.privs | default(omit) }}"
    schema: "{{ item.schema | default('public') }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ item.port | default(omit) }}"
    type: "{{ item.type | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_privs }}"
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true